"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000";
type Device = { id: number; name: string };
type Connection = { id: number; device_a_name: string; interface_a: string | null; device_b_name: string; interface_b: string | null; relationship_type: string; source: string; confidence: number; observed_at: string };
const blank = { device_a_id: "", interface_a: "", device_b_id: "", interface_b: "", relationship_type: "uplink" };

export default function ConnectionsPage() {
  const [devices, setDevices] = useState<Device[]>([]); const [connections, setConnections] = useState<Connection[] | null>(null); const [form, setForm] = useState(blank); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { try { const [site, links] = await Promise.all([fetch(`${API_URL}/api/sites/pj-office`), fetch(`${API_URL}/api/sites/pj-office/connections`)]); if (!site.ok || !links.ok) throw new Error("RackScan could not load documented connections."); setDevices((await site.json()).devices_list); setConnections(await links.json()); } catch (cause) { setError(cause instanceof Error ? cause.message : "RackScan could not load connections."); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form.device_b_id) { setError("Choose the destination device."); return; } setBusy(true); setError(""); try { const response = await fetch(`${API_URL}/api/sites/pj-office/connections`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, device_a_id: form.device_a_id ? Number(form.device_a_id) : null, device_b_id: Number(form.device_b_id) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "Connection could not be recorded."); setForm(blank); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Connection could not be recorded."); } finally { setBusy(false); } }
  return <main className="connections-page"><header className="evidence-header"><Link href="/">← Back to site overview</Link><span className="eyebrow">PHASE 1 / CONNECTIONS</span><h1>Document observed links</h1><p>Manual connections are evidence-backed records. RackScan never infers an unobserved link.</p></header>{error && <p className="import-error" role="alert">{error} <button onClick={() => void load()}>Retry</button></p>}<section className="connection-workbench"><form className="connection-form" onSubmit={submit}><div><span className="eyebrow">MANUAL EVIDENCE</span><h2>Record a connection</h2><p>Use “Internet” when the first endpoint is outside the documented site.</p></div><label>From<select value={form.device_a_id} onChange={event => setForm({ ...form, device_a_id: event.target.value })}><option value="">Internet / external</option>{devices.map(device => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label><label>From interface<input value={form.interface_a} onChange={event => setForm({ ...form, interface_a: event.target.value })} placeholder="e.g. Port 24" /></label><label>To device<select required value={form.device_b_id} onChange={event => setForm({ ...form, device_b_id: event.target.value })}><option value="">Choose a device</option>{devices.map(device => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label><label>To interface<input value={form.interface_b} onChange={event => setForm({ ...form, interface_b: event.target.value })} placeholder="e.g. Port 48" /></label><button className="primary" disabled={busy}>{busy ? "Recording…" : "Record connection"}</button></form><section className="connection-list"><div className="proposal-heading"><div><span className="eyebrow">ACCEPTED RELATIONSHIPS</span><h2>{connections === null ? "Loading…" : `${connections.length} documented links`}</h2></div></div>{connections?.length ? connections.map(link => <article className="connection-row" key={link.id}><strong>{link.device_a_name}<small>{link.interface_a ?? "Interface unknown"}</small></strong><b>↔</b><strong>{link.device_b_name}<small>{link.interface_b ?? "Interface unknown"}</small></strong><span>{link.source}<small>{link.confidence}% · {link.observed_at}</small></span></article>) : <div className="evidence-empty"><span>⌁</span><h2>No recorded links</h2><p>Record the first observed relationship to build a topology.</p></div>}</section></section></main>;
}
